/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Tribbler_TYPES_H
#define Tribbler_TYPES_H

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>



namespace Tribbler {

struct TribbleStatus {
  enum type {
    OK = 1,
    EEXISTS = 2,
    INVALID_USER = 3,
    INVALID_SUBSCRIBETO = 4,
    NOT_IMPLEMENTED = 5
  };
};

extern const std::map<int, const char*> _TribbleStatus_VALUES_TO_NAMES;

typedef struct _Tribble__isset {
  _Tribble__isset() : userid(false), posted(false), contents(false) {}
  bool userid;
  bool posted;
  bool contents;
} _Tribble__isset;

class Tribble {
 public:

  static const char* ascii_fingerprint; // = "FA35BEC6F4D26D79A7E0AD1366489BCC";
  static const uint8_t binary_fingerprint[16]; // = {0xFA,0x35,0xBE,0xC6,0xF4,0xD2,0x6D,0x79,0xA7,0xE0,0xAD,0x13,0x66,0x48,0x9B,0xCC};

  Tribble() : userid(), posted(0), contents() {
  }

  virtual ~Tribble() throw() {}

  std::string userid;
  int64_t posted;
  std::string contents;

  _Tribble__isset __isset;

  void __set_userid(const std::string& val) {
    userid = val;
  }

  void __set_posted(const int64_t val) {
    posted = val;
  }

  void __set_contents(const std::string& val) {
    contents = val;
  }

  bool operator == (const Tribble & rhs) const
  {
    if (!(userid == rhs.userid))
      return false;
    if (!(posted == rhs.posted))
      return false;
    if (!(contents == rhs.contents))
      return false;
    return true;
  }
  bool operator != (const Tribble &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Tribble & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(Tribble &a, Tribble &b);

typedef struct _TribbleResponse__isset {
  _TribbleResponse__isset() : tribbles(false), status(false) {}
  bool tribbles;
  bool status;
} _TribbleResponse__isset;

class TribbleResponse {
 public:

  static const char* ascii_fingerprint; // = "43BFF501D78BB9C8F03213B50B38B34D";
  static const uint8_t binary_fingerprint[16]; // = {0x43,0xBF,0xF5,0x01,0xD7,0x8B,0xB9,0xC8,0xF0,0x32,0x13,0xB5,0x0B,0x38,0xB3,0x4D};

  TribbleResponse() : status((TribbleStatus::type)0) {
  }

  virtual ~TribbleResponse() throw() {}

  std::vector<Tribble>  tribbles;
  TribbleStatus::type status;

  _TribbleResponse__isset __isset;

  void __set_tribbles(const std::vector<Tribble> & val) {
    tribbles = val;
  }

  void __set_status(const TribbleStatus::type val) {
    status = val;
  }

  bool operator == (const TribbleResponse & rhs) const
  {
    if (!(tribbles == rhs.tribbles))
      return false;
    if (!(status == rhs.status))
      return false;
    return true;
  }
  bool operator != (const TribbleResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TribbleResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(TribbleResponse &a, TribbleResponse &b);

typedef struct _SubscriptionResponse__isset {
  _SubscriptionResponse__isset() : subscriptions(false), status(false) {}
  bool subscriptions;
  bool status;
} _SubscriptionResponse__isset;

class SubscriptionResponse {
 public:

  static const char* ascii_fingerprint; // = "86398F2299656EAB855B1FD290A7B0C1";
  static const uint8_t binary_fingerprint[16]; // = {0x86,0x39,0x8F,0x22,0x99,0x65,0x6E,0xAB,0x85,0x5B,0x1F,0xD2,0x90,0xA7,0xB0,0xC1};

  SubscriptionResponse() : status((TribbleStatus::type)0) {
  }

  virtual ~SubscriptionResponse() throw() {}

  std::vector<std::string>  subscriptions;
  TribbleStatus::type status;

  _SubscriptionResponse__isset __isset;

  void __set_subscriptions(const std::vector<std::string> & val) {
    subscriptions = val;
  }

  void __set_status(const TribbleStatus::type val) {
    status = val;
  }

  bool operator == (const SubscriptionResponse & rhs) const
  {
    if (!(subscriptions == rhs.subscriptions))
      return false;
    if (!(status == rhs.status))
      return false;
    return true;
  }
  bool operator != (const SubscriptionResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SubscriptionResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(SubscriptionResponse &a, SubscriptionResponse &b);

} // namespace

#endif
